set_property PACKAGE_PIN F22 [get_ports a]
set_property PACKAGE_PIN G22 [get_ports b]
set_property PACKAGE_PIN T22 [get_ports c]
set_property PACKAGE_PIN Y9 [get_ports clk]
set_property PACKAGE_PIN T22 [get_ports q]
set_property PACKAGE_PIN P16 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports c]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports q]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

set_property IOSTANDARD LVCMOS33 [get_ports button_sub]
set_property IOSTANDARD LVCMOS33 [get_ports button_add]
set_property PACKAGE_PIN T18 [get_ports button_add]
set_property PACKAGE_PIN R16 [get_ports button_sub]

set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
set_property PACKAGE_PIN U14 [get_ports {LED[6]}]
set_property PACKAGE_PIN U19 [get_ports {LED[5]}]
set_property PACKAGE_PIN W22 [get_ports {LED[4]}]
set_property PACKAGE_PIN V22 [get_ports {LED[3]}]
set_property PACKAGE_PIN U21 [get_ports {LED[2]}]
set_property PACKAGE_PIN U22 [get_ports {LED[1]}]
set_property PACKAGE_PIN T21 [get_ports {LED[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports led_out]
set_property IOSTANDARD LVCMOS33 [get_ports {led_order[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_order[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_order[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_order[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_order[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_order[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_order[0]}]
set_property PACKAGE_PIN T22 [get_ports led_out]
set_property PACKAGE_PIN U14 [get_ports {led_order[6]}]
set_property PACKAGE_PIN U19 [get_ports {led_order[5]}]
set_property PACKAGE_PIN W22 [get_ports {led_order[4]}]
set_property PACKAGE_PIN V22 [get_ports {led_order[3]}]
set_property PACKAGE_PIN U21 [get_ports {led_order[2]}]
set_property PACKAGE_PIN U22 [get_ports {led_order[1]}]
set_property PACKAGE_PIN T21 [get_ports {led_order[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {seg1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {seg2[0]}]
set_property PACKAGE_PIN AB2 [get_ports {seg1[3]}]
set_property PACKAGE_PIN AA7 [get_ports {seg1[2]}]
set_property PACKAGE_PIN AB11 [get_ports {seg1[1]}]
set_property PACKAGE_PIN AA11 [get_ports {seg1[0]}]
set_property PACKAGE_PIN Y11 [get_ports {seg2[3]}]
set_property PACKAGE_PIN AA6 [get_ports {seg2[2]}]
set_property PACKAGE_PIN AB9 [get_ports {seg2[1]}]
set_property PACKAGE_PIN AB10 [get_ports {seg2[0]}]
